version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app:ro
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000  --reload"
  postgres:
    image: postgres:15-alpine  # Можно выбрать другую версию (например, latest, 16, 14)
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres      # Имя пользователя по умолчанию
      POSTGRES_PASSWORD: postgres  # Пароль (в продакшене используйте сложный!)
      POSTGRES_DB: mydatabase      # Имя базы данных по умолчанию
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные между перезапусками
    ports:
      - "5432:5432"  # Пробрасываем порт наружу (host:container)
    restart: unless-stopped  # Автоматически перезапускать контейнер при падении
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:  # Именованный том для хранения данных